
src-git helloworld https://github.com/fw876/helloworld' >>feeds.conf.default
src-git syncthing https://github.com/syncthing/syncthing' >>feeds.conf.default
src-git diskman https://github.com/immortalwrt/luci/tree/master/applications/luci-app-diskman' >>feeds.conf.default
src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages' >>feeds.conf.default
src-git passwall_luci https://github.com/Openwrt-Passwall/openwrt-passwall' >>feeds.conf.defaul
