src-include defaults feeds.conf.default
src-git helloworld https://github.com/fw876/helloworld
src-git syncthing https://github.com/syncthing/syncthing
src-git diskman https://github.com/immortalwrt/luci/tree/master/applications/luci-app-diskman
src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages
src-git passwall_luci https://github.com/Openwrt-Passwall/openwrt-passwall
